# Staff+ | Made with love by Shortninja - ?
# 
# If you're having trouble with item type names, refer to here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# All item slots are how they "should be", meaning the first slot of an inventory will be one. Maximum is 36.

disable-packets: false
metrics: true
lang: lang_en
blocked-commands: /example1, /example2, /example3
blocked-mode-commands: /example1, /example2, /example3
glass-color: 0
glass-title: '&bChoose GUI glass color'
reports-module:
  enabled: true
  sound: ORB_PICKUP
  cooldown: 10
  show-reporter: true
warnings-module:
  enabled: true
  sound: ORB_PICKUP
  maximum: 3
  ban-command: ban %player% Three warnings limit reached.
  clear: 604800
  show-issuer: true
staff-chat-module:
  enabled: true
  handle: '#'
vanish-module:
  enabled: true
  tab-list: true
  show-away: false
chat-module:
  enabled: true
  lines: 100
  slow: 5
  blacklist-module:
    enabled: true
    hoverable: true
    character: '*'
    merging: true
    words: cunt, fag, faggot, slut, nigger, nigga
    characters: 卍, 卐
    domains: com, net, org, co
    periods: (), (dot),
    allowed: ass
tickets-module:
  enabled: true
  global: false
  keep-open: true
alerts-module:
  name-notify: true
  mention-notify: true
  sound: ORB_PICKUP
  xray-alerts:
    enabled: true
    blocks: SPAWNER, DIAMOND_ORE, DRAGON_EGG, EMERALD_ORE, BEACON, SPONGE, PRISMARINE,
      SEA_LANTERN, BEDROCK, END_PORTAL, END_PORTAL_FRAME, COMMAND_BLOCK
staff-mode:
  damage: false
  hunger-loss: false
  enable-commands: example1 %player%, example2 %player%
  disable-commands: example1 %player%, example2 %player%
  disable-on-world-change: false
  block-manipulation: true
  inventory-interaction: false
  item-change: true
  vanish-type: TOTAL
  invincible: true
  flight: true
  creative: true
  original-location: true
  enable-on-login: false
  compass-module:
    enabled: true
    slot: 1
    velocity: 5
    item: COMPASS
    name: '&4Launcher'
    lore: '&7Launches you towards the, &7location you are facing.'
  random-teleport-module:
    enabled: true
    slot: 2
    item: ENDER_EYE
    name: '&cRandom Teleport'
    lore: '&7Teleports you to a random player.'
    random: false
  vanish-module:
    enabled: false
    slot: 3
    item: INK_SAC
    name: '&6Vanish'
    lore: '&7Toggles your total vanish.'
    item-off: INK_SAC
  gui-module:
    enabled: true
    slot: 4
    item: PAPER
    name: '&eGUI Hub'
    lore: '&7Opens the GUI hub.'
    reports-gui: true
    reports-title: '&bUnresolved reports'
    miner-gui: true
    miner-title: '&bUnderground users'
    xray-level: 32
  counter-module:
    enabled: true
    slot: 5
    item: SKELETON_SKULL
    name: '&aStaff List'
    lore: '&7Shows all staff online and in staff mode'
    title: '&bCurrent staff online'
    show-staff-mode: false
  freeze-module:
    timer: 5
    sound: ORB_PICKUP
    logout-commands: ban %player%
    enabled: true
    slot: 6
    item: BLAZE_ROD
    name: '&2Freeze'
    lore: '&7Toggles freeze for the clicked player.'
    chat: true
    damage: false
    prompt: false
    prompt-title: '&bFrozen'
  cps-module:
    enabled: true
    slot: 7
    item: CLOCK
    name: '&3CPS'
    lore: '&7Runs a click per second test on, the player that was clicked.'
    time: 10
    max: 15.0
  examine-module:
    enabled: true
    slot: 8
    item: CHEST
    name: '&bExamine'
    lore: '&7Inspects the inventory of the player that was clicked.'
    title: '&bExamine inventory'
    info-line:
      food: 2
      ip-address: 3
      gamemode: 4
      infractions: 5
      location: 6
      notes: 7
      freeze: 8
      warn: 0
  follow-module:
    enabled: true
    slot: 9
    item: LEAD
    name: '&9Follow'
    lore: '&7Mounts the player that was clicked.'
    use-mount: true
  custom-modules:
    StaticCommand:
      enabled: true
      type: COMMAND_STATIC
      slot: 3
      item: INK_SAC
      name: '&6Vanish'
      lore: '&7Toggles your total vanish.'
      item-off: INK_SAC
      command: sv
    DynamicCommand:
      enabled: false
      type: COMMAND_DYNAMIC
      slot: 31
      item: QUARTZ
      name: '&4Ban this kid'
      lore: '&cyou damn lazy staff'
      command: ban %clicked% &6for shitposting too much with %clicker%
    ConsoleCommand:
      enabled: false
      type: COMMAND_CONSOLE
      slot: 33
      item: OBSIDIAN
      name: '&bDisable staff mode'
      lore: '&7Boop'
      command: staff %clicker% disable
    Item:
      enabled: false
      type: ITEM
      slot: 34
      item: WOOD_AXE
      name: '&7WorldEdit Wand'
      lore: '&8don''t grief shitlord!!'
permissions:
  strip: staff.strip
  tp: staff.tp
  staffplus: staff.staffplus
  ipPerm: staff.staffplus.hideip
  invClear: staff.staffplus.clearinv
  wild-card: staff.*
  block: staff.block
  report: staff.report
  report-bypass: staff.report.bypass
  warn: staff.warn
  warn-bypass: staff.warn.bypass
  staff-chat: staff.staffchat
  vanish-total: staff.vanish.total
  vanish-list: staff.vanish.list
  chat-clear: staff.chat.clear
  chat-toggle: staff.chat.toggle
  chat-slow: staff.chat.slow
  blacklist: staff.blacklist
  tickets: staff.tickets
  mention: staff.alerts.mention
  name-change: staff.alerts.namechange
  xray: staff.alerts.xray
  mode: staff.mode
  compass: staff.compass
  random-teleport: staff.random-teleport
  gui: staff.gui
  counter: staff.counter
  freeze: staff.freeze
  freeze-bypass: staff.freeze.bypass
  cps: staff.cps
  examine: staff.examine
  examine-modify: staff.examine.modify
  follow: staff.follow
  lockdown: staff.lockdown
  revive: staff.revive
  member: staff.member
commands:
  login: login
  register: register
  strip: strip
  clearInv: clear
  staff-mode: staff
  freeze: freeze
  examine: examine
  notes: notes
  cps: cps
  staff-chat: staffchat
  report: report
  warn: warn
  vanish: poopvanish
  chat: chat
  ticket: ticket
  alerts: alerts
  follow: follow
  revive: revive
  staff-list: personnel
config-version: 6201
auto-save: 3600
clock: 2
animation-packets: PacketPlayOutBlockBreakAnimation, PacketPlayOutBlockAction
sound-names: random.chestopen, random.chestclosed
login:
  enabled: false
  kick-message: '&cInvalid login password!'
storage:
  type: flatfile
  mysql:
    host: localhost
    user: root
    database: root
    password: mypass
    port: 3306
    migrated: false
